-- ==========================================
-- SCRIPT DE CRIAÇÃO DO BANCO DE DADOS SUPABASE (PostgreSQL)
-- PROJETO: Leão Kids
-- Copie e cole este script no SQL Editor do seu painel do Supabase.
-- ==========================================

-- 1. Perfis das Crianças
CREATE TABLE IF NOT EXISTS children_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_boy BOOLEAN NOT NULL, -- True: Cosmos, False: Magia
    avatar_url TEXT NOT NULL,
    creation_time BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
    parent_email TEXT NOT NULL
);

-- 2. Vídeos Aprovados/Liberados pelos Pais
CREATE TABLE IF NOT EXISTS approved_videos (
    id TEXT NOT NULL, -- ID do vídeo do YouTube (11 caracteres)
    parent_email TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    duration_text TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    PRIMARY KEY (id, parent_email)
);

-- 3. Playlists das Crianças
CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    parent_email TEXT NOT NULL
);

-- 4. Vídeos dentro das Playlists
CREATE TABLE IF NOT EXISTS playlist_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    parent_email TEXT NOT NULL
);

-- 5. Vídeos Favoritados pelas Crianças
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    timestamp BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
    parent_email TEXT NOT NULL
);

-- 6. Histórico de Exibição
CREATE TABLE IF NOT EXISTS history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    timestamp BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
    watched_duration_seconds BIGINT NOT NULL,
    parent_email TEXT NOT NULL
);

-- 7. Palavras Bloqueadas (Blacklist de Termos)
CREATE TABLE IF NOT EXISTS blocked_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT NOT NULL,
    parent_email TEXT NOT NULL,
    UNIQUE (word, parent_email)
);

-- 8. Canais do YouTube Bloqueados
CREATE TABLE IF NOT EXISTS blocked_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL,
    parent_email TEXT NOT NULL,
    UNIQUE (channel_name, parent_email)
);

-- 9. Canais do YouTube Permitidos (Modo Restrito)
CREATE TABLE IF NOT EXISTS allowed_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL,
    parent_email TEXT NOT NULL,
    UNIQUE (channel_name, parent_email)
);

-- 10. Histórico de Tentativas de Busca Bloqueadas (Controle Parental)
CREATE TABLE IF NOT EXISTS search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    query TEXT NOT NULL,
    timestamp BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
    parent_email TEXT NOT NULL
);

-- 11. Configuração de Controle dos Pais
CREATE TABLE IF NOT EXISTS parent_config (
    connected_email TEXT PRIMARY KEY,
    pin_code TEXT NOT NULL DEFAULT '1234',
    screen_time_limit_minutes INT NOT NULL DEFAULT 60,
    is_strict_channel_mode BOOLEAN NOT NULL DEFAULT FALSE,
    is_smart_curator_mode BOOLEAN NOT NULL DEFAULT FALSE,
    connected_name TEXT,
    connected_photo TEXT
);
