-- ==========================================
-- SCRIPT DE CRIAÇÃO DO BANCO DE DADOS SUPABASE (PostgreSQL)
-- PROJETO: Leão Kids
-- Copie e cole este script no SQL Editor do seu painel do Supabase.
-- ==========================================

-- 1. Perfis das Crianças
CREATE TABLE IF NOT EXISTS children_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_boy BOOLEAN NOT NULL, -- True: Cosmos, False: Magia
    avatar_url TEXT NOT NULL,
    creation_time BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT
);

-- 2. Vídeos Aprovados/Liberados pelos Pais
CREATE TABLE IF NOT EXISTS approved_videos (
    id TEXT PRIMARY KEY, -- ID do vídeo do YouTube (11 caracteres)
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    duration_text TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL
);

-- 3. Playlists das Crianças
CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

-- 4. Vídeos dentro das Playlists
CREATE TABLE IF NOT EXISTS playlist_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL
);

-- 5. Vídeos Favoritados pelas Crianças
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    timestamp BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT
);

-- 6. Histórico de Exibição
CREATE TABLE IF NOT EXISTS history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    timestamp BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
    watched_duration_seconds BIGINT NOT NULL
);

-- 7. Palavras Bloqueadas (Blacklist de Termos)
CREATE TABLE IF NOT EXISTS blocked_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT NOT NULL UNIQUE
);

-- 8. Canais do YouTube Bloqueados
CREATE TABLE IF NOT EXISTS blocked_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL UNIQUE
);

-- 9. Canais do YouTube Permitidos (Modo Restrito)
CREATE TABLE IF NOT EXISTS allowed_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL UNIQUE
);

-- 10. Histórico de Tentativas de Busca Bloqueadas (Controle Parental)
CREATE TABLE IF NOT EXISTS search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES children_profiles(id) ON DELETE CASCADE,
    query TEXT NOT NULL,
    timestamp BIGINT DEFAULT (extract(epoch from now()) * 1000)::BIGINT
);

-- 11. Configuração de Controle dos Pais (Garante apenas 1 linha)
CREATE TABLE IF NOT EXISTS parent_config (
    id BIGINT PRIMARY KEY DEFAULT 1,
    pin_code TEXT NOT NULL DEFAULT '1234',
    screen_time_limit_minutes INT NOT NULL DEFAULT 60,
    is_strict_channel_mode BOOLEAN NOT NULL DEFAULT FALSE,
    is_smart_curator_mode BOOLEAN NOT NULL DEFAULT FALSE,
    connected_email TEXT,
    connected_name TEXT,
    connected_photo TEXT,
    CONSTRAINT single_row CHECK (id = 1)
);

-- ==========================================
-- PRÉ-CARREGAR CONFIGURAÇÕES E FILTROS PADRÃO
-- ==========================================

-- Inserir Configuração Inicial
INSERT INTO parent_config (id, pin_code, screen_time_limit_minutes, is_strict_channel_mode, is_smart_curator_mode)
VALUES (1, '1234', 60, FALSE, FALSE)
ON CONFLICT (id) DO NOTHING;

-- Preencher Palavras Bloqueadas Iniciais
INSERT INTO blocked_words (word) VALUES
('Luta'), ('Horror'), ('Assustador'), ('Morte'), ('Sangue'), ('Violência'), ('Terror'), ('Arma'), ('Monstro'), ('Crime'), ('Demônio')
ON CONFLICT (word) DO NOTHING;

-- Preencher Canais Permitidos Iniciais
INSERT INTO allowed_channels (channel_name) VALUES
('Galinha Pintadinha'), ('Manual do Mundo'), ('Mundo Bita'), ('NASA'), ('National Geographic Kids')
ON CONFLICT (channel_name) DO NOTHING;
